### ISSUE TITLE
(PDF) IHO S-102: Overlapping table cells and exaggerated horizontal separation in description lists

### ISSUE THREAD

**Issue by manuelfuenmayor** [metanorma/metanorma-iho#116]
In relation to https://github.com/metanorma/S-102-Product-Specification/issues/12

Document S-102 shows multiple instances of overlapping table cells:

![issue-1](https://user-images.githubusercontent.com/33627611/220406405-a1b0da87-2d94-4d85-93b0-5df61d712c9b.PNG)

And exaggerated horizontal separation in description lists:

![issue-2](https://user-images.githubusercontent.com/33627611/220406528-52dad57f-b8c7-45c5-98af-e904a86f772b.PNG)

**Comment by Intelligent2013** [comment]
I've fixed the issue almost. It's working for all tables, except one:
![image](https://user-images.githubusercontent.com/5559926/221031369-cb94f0cd-4ce5-43f6-a4a5-324b98e0a497.png)

In process yet...

**Comment by Intelligent2013** [comment]
Fixed:
![image](https://user-images.githubusercontent.com/5559926/221255227-e62da824-e0e3-41d5-b605-ac9fdb08a109.png)

**Comment by manuelfuenmayor** [comment]
@Intelligent2013, there are still some overlapping cells:
![issue5](https://user-images.githubusercontent.com/33627611/221280294-c11bc52e-3d99-4c6b-8600-ba0745204dc6.PNG)


![issue6](https://user-images.githubusercontent.com/33627611/221280312-58e8cae5-401a-476d-9fcf-0a043395bea1.PNG)

**Comment by manuelfuenmayor** [comment]
In addition, there is too much of horizontal space in between bibliography number and its corresponding title:

![issue3](https://user-images.githubusercontent.com/33627611/221280590-4757ce03-7ccd-4392-95b6-dc84d2fa8852.PNG)

Also, this issue persists:

![broken-1](https://user-images.githubusercontent.com/33627611/219097006-0e7c9f10-fdb5-4023-881a-85e67f41d71b.PNG)

Can it be fixed?

**Comment by Intelligent2013** [comment]
> there are still some overlapping cells:

@manuelfuenmayor this happens due 'indivisible' words in each table cells:
- attribute
- spatialRepresentationType
- SpatialRepresentationType
- SpatialRepresentationType

![image](https://user-images.githubusercontent.com/5559926/221345693-577129af-0d56-482e-8a72-fe3e5da8e4c7.png)

The 'Table 22' renders ok in the landscape mode:
![image](https://user-images.githubusercontent.com/5559926/221345877-73cb11fc-1cdc-4b47-831f-34ef52350b50.png)

**Comment by Intelligent2013** [comment]
> In addition, there is too much of horizontal space in between bibliography number and its corresponding title:

This wide space was made specially to fit the doc identifier as in the original PDF (https://github.com/metanorma/mn-samples-iho/blob/main/reference-docs/s-102/S-102_EN_Bathymetric%20Surface%20Product%20Specification_Ed2.0.0.pdf):
![image](https://user-images.githubusercontent.com/5559926/221346110-fcca4e5d-3365-4f72-89f0-83e26c8efbb1.png)

I don't sure that `[1]`, `[2]`... is a right identifier, because in the text we have standards numbers as the references, but not `[digits]`:
![image](https://user-images.githubusercontent.com/5559926/221346180-2d839025-6046-43c7-b16b-7d4a34fddd31.png)

**Comment by Intelligent2013** [comment]
Here is previously generated PDF example from Nov 30, 2022:
![image](https://user-images.githubusercontent.com/5559926/221346398-804b5772-9e82-4b8d-81fc-decf3c788ab3.png)

**Comment by Intelligent2013** [comment]
> Also, this issue persists:
> 
> ![broken-1](https://user-images.githubusercontent.com/33627611/219097006-0e7c9f10-fdb5-4023-881a-85e67f41d71b.PNG)
>
> Can it be fixed?

Dot is the word break separator. I'll try to redefine this behaviour - if previous char is empty or space, and next is digit, then keep them together.

**Comment by Intelligent2013** [comment]
The same issue in the `Table 25`:
![image](https://user-images.githubusercontent.com/5559926/221353385-aa48e981-cc0e-450c-b0f3-48a0b831d708.png)

Need switch to the landscape mode.

**Comment by Intelligent2013** [comment]
No issue in `Table 25`. I've used wrong xml.

**Comment by Intelligent2013** [comment]
Done:
![image](https://user-images.githubusercontent.com/5559926/221360304-56ddf56e-66a7-41f0-a1a8-ab4efbba6ca5.png)

**Comment by manuelfuenmayor** [comment]
Hi @Intelligent2013, thanks for your rapid answer:

> this happens due 'indivisible' words in each table cells:

Ok, I see... Yeah well, in original source, I note that they extend the width of the table beyond the limits of the margin. So that may be a reason for they to fit the content without any overlapping.

> This wide space was made specially to fit the doc identifier as in the original PDF

Ok, I wasn't aware of that. All good then.

> Done:

I've confirmed it. Thanks!

**Comment by manuelfuenmayor** [comment]
I think we are done here. Thanks @Intelligent2013.
